#
# Amini - Server Config file
#

network.url: http://amini.eastus.cloudapp.azure.com:8546
# network.url: http://amini.canadaeast.cloudapp.azure.com:8546
# network.url: https://andricdu.by.ether.camp:8555/sandbox/d51e67a7fb
# network.url: https://amini.by.ether.camp:8555/sandbox/df7558b136

index.server: amini.canadaeast.cloudapp.azure.com
