#
# Amini - Server Config file
#

# https://amini.by.ether.camp:8555/sandbox/df7558b136
network.url: https://andricdu.by.ether.camp:8555/sandbox/d51e67a7fb

index.server: amini.canadaeast.cloudapp.azure.com
